version: '3.8'

services:
  web:
    build: .
    ports:
      - "6500:6500"
    environment:
      - DB_HOST=127.0.0.1  # 替换为实际MySQL服务器IP
      - DB_USER=student          # 替换为实际数据库用户
      - DB_PASSWORD=15916188538 # 替换为实际数据库密码
      - DB_NAME=student_system
    restart: always